import Link from 'next/link';
import { notFound } from 'next/navigation';
import type { CSSProperties } from 'react';
import type { Metadata } from 'next';
import { getPropertyBySlug, getPropertySlugs } from '@/lib/properties';
import { dynamicSeoMetadata } from '@/lib/seo';
import PropertyGallery from '@/components/PropertyGallery';
import ShareButton from '@/components/ShareButton';
import PropertyQr from '@/components/PropertyQr';
import ContentTable from '@/components/ContentTable';

export async function generateStaticParams() {
  const slugs = await getPropertySlugs();
  return slugs.map((slug) => ({ slug }));
}

export async function generateMetadata({ params }: { params: { slug: string } }): Promise<Metadata> {
  const property = await getPropertyBySlug(params.slug);
  if (!property) return { title: 'Property' };

  const path = `/properties/${property.slug}`;
  const base = dynamicSeoMetadata(path, {
    title: property.name,
    description: `${property.name} in ${property.location}. ${property.type}, from ${property.price}.`,
  });

  // Plain-string title/description for the social cards (base.title may be an
  // { absolute } object when the SEO sheet supplies a full title tag).
  const shareTitle =
    typeof base.title === 'object' && base.title && 'absolute' in base.title
      ? String(base.title.absolute)
      : String(base.title ?? property.name);
  const shareDescription = String(base.description ?? '');

  // Point the social-share image at the property's own photo so WhatsApp,
  // iMessage, etc. show the listing rather than the site-wide brand card
  // generated by app/opengraph-image.tsx. Route-level openGraph.images wins
  // over the file-based default for this page.
  const images = property.img
    ? [{ url: property.img, width: 800, height: 600, alt: property.name }]
    : undefined;

  return {
    ...base,
    openGraph: {
      type: 'website',
      title: shareTitle,
      description: shareDescription,
      url: path,
      images,
    },
    twitter: {
      card: 'summary_large_image',
      title: shareTitle,
      description: shareDescription,
      images: property.img ? [property.img] : undefined,
    },
  };
}

export default async function PropertyPage({ params }: { params: { slug: string } }) {
  const property = await getPropertyBySlug(params.slug);
  if (!property) notFound();

  // Marketing can supply a keyword-led H1 that differs from the short card name.
  // Either way the listing head sizes itself from the character count so the
  // title sits on a single line (it wraps below 700px, per globals.css).
  const heading = property.heading || property.name;

  // Gold line under the H1, e.g. "4 Bedroom Villa For Rent". The count comes off
  // the front of `beds` ('4 Bed · 4 Bath'); studios and plots carry no count
  // there, so they read as "Studio For Rent" / "Residential Plot For Sale".
  const bedCount = property.beds.match(/^(\d+)\s*Bed/i)?.[1];
  const subhead = `${bedCount ? `${bedCount} Bedroom ` : ''}${property.type} ${property.tag}`;

  // Both gold lines size themselves from their own character count so each
  // holds a single row on phones (see .page-head--listing .eyebrow).
  const eyebrow = `${property.tag} · ${property.location}`;

  return (
    <article>
      {/* ===== HEADER ===== */}
      <section className="page-head page-head--listing">
        <div className="wrap">
          <span
            className="eyebrow reveal"
            style={{ display: 'block', marginBottom: 14, '--eyebrow-len': eyebrow.length } as CSSProperties}
          >
            {eyebrow}
          </span>
          <h1
            className={`reveal${property.heading ? ' h1-seo' : ''}`}
            style={{ '--title-len': heading.length } as CSSProperties}
          >
            {heading}
          </h1>
          <span
            className="eyebrow reveal"
            style={{ display: 'block', marginTop: 14, '--eyebrow-len': subhead.length } as CSSProperties}
          >
            {subhead}
          </span>
        </div>
      </section>

      {/* ===== DETAIL ===== */}
      <section className="section-light" style={{ paddingTop: 44 }}>
        <div className="wrap">
          <Link href="/properties" className="back-link">← Back to all properties</Link>

          <div className="property-detail">
            <PropertyGallery
              images={property.gallery && property.gallery.length ? property.gallery : [property.img]}
              alt={property.name}
            />

            <div className="reveal">
              <div className="prop-price-row">
                <div className="prop-price">From {property.price}</div>
                <ShareButton
                  title={`${property.name} — Earth Link Real Estate`}
                  text={`${property.name} in ${property.location}. ${property.type}, from ${property.price}.`}
                />
              </div>

              <dl className="detail-spec">
                <div><dt>Type</dt><dd>{property.type}</dd></div>
                <div><dt>Bedrooms</dt><dd>{property.beds}</dd></div>
                <div><dt>Area</dt><dd>{property.area}</dd></div>
                <div><dt>Location</dt><dd>{property.location}</dd></div>
                <div><dt>Reference</dt><dd>{property.ref}</dd></div>
                <div><dt>DLD Permit</dt><dd>{property.permit}</dd></div>
              </dl>

              {property.descriptionHeading && (
                <h2
                  style={{
                    fontSize: 'clamp(1.15rem, 3.4vw, 1.4rem)',
                    fontWeight: 700,
                    lineHeight: 1.3,
                    color: 'var(--champagne-ink)',
                    marginBottom: 14,
                  }}
                >
                  {property.descriptionHeading}
                </h2>
              )}

              {property.description.map((paragraph, i) => (
                <p className="prose" key={i} style={{ marginBottom: 16 }}>
                  {paragraph}
                </p>
              ))}

              {property.tables?.map((table, i) => (
                <ContentTable key={table._key ?? i} value={table} />
              ))}

              <div className="hero-btns" style={{ marginTop: 30 }}>
                <Link href="/contact" className="btn btn-gold">Enquire about this property</Link>
                <Link href="/properties" className="btn btn-glass">View all properties</Link>
              </div>

              {property.permitUrl && (
                <div style={{ marginTop: 30 }}>
                  <PropertyQr url={property.permitUrl} />
                  <p className="table-note" style={{ marginTop: 12 }}>
                    Trakheesi Permit — scan to verify with the Dubai Land Department
                  </p>
                </div>
              )}

              <p className="table-note" style={{ marginTop: 24 }}>
                Listed by Earth Link Real Estate. Contact us for the DLD permit and full documentation.
              </p>
            </div>
          </div>
        </div>
      </section>
    </article>
  );
}
