import Link from 'next/link';
import { notFound } from 'next/navigation';
import type { Metadata } from 'next';
import { getPropertyBySlug, getPropertySlugs } from '@/lib/properties';
import { dynamicSeoMetadata } from '@/lib/seo';
import PropertyGallery from '@/components/PropertyGallery';
import ShareButton from '@/components/ShareButton';
import PropertyQr from '@/components/PropertyQr';

export async function generateStaticParams() {
  const slugs = await getPropertySlugs();
  return slugs.map((slug) => ({ slug }));
}

export async function generateMetadata({ params }: { params: { slug: string } }): Promise<Metadata> {
  const property = await getPropertyBySlug(params.slug);
  if (!property) return { title: 'Property' };

  const path = `/properties/${property.slug}`;
  const base = dynamicSeoMetadata(path, {
    title: property.name,
    description: `${property.name} in ${property.location}. ${property.type}, from ${property.price}.`,
  });

  // Plain-string title/description for the social cards (base.title may be an
  // { absolute } object when the SEO sheet supplies a full title tag).
  const shareTitle =
    typeof base.title === 'object' && base.title && 'absolute' in base.title
      ? String(base.title.absolute)
      : String(base.title ?? property.name);
  const shareDescription = String(base.description ?? '');

  // Point the social-share image at the property's own photo so WhatsApp,
  // iMessage, etc. show the listing rather than the site-wide brand card
  // generated by app/opengraph-image.tsx. Route-level openGraph.images wins
  // over the file-based default for this page.
  const images = property.img
    ? [{ url: property.img, width: 800, height: 600, alt: property.name }]
    : undefined;

  return {
    ...base,
    openGraph: {
      type: 'website',
      title: shareTitle,
      description: shareDescription,
      url: path,
      images,
    },
    twitter: {
      card: 'summary_large_image',
      title: shareTitle,
      description: shareDescription,
      images: property.img ? [property.img] : undefined,
    },
  };
}

export default async function PropertyPage({ params }: { params: { slug: string } }) {
  const property = await getPropertyBySlug(params.slug);
  if (!property) notFound();

  return (
    <article>
      {/* ===== HEADER ===== */}
      <section className="page-head">
        <div className="wrap">
          <span className="eyebrow reveal" style={{ display: 'block', marginBottom: 14 }}>
            {property.tag} · {property.location}
          </span>
          <h1 className="reveal">{property.name}</h1>
        </div>
      </section>

      {/* ===== DETAIL ===== */}
      <section className="section-light" style={{ paddingTop: 44 }}>
        <div className="wrap">
          <Link href="/properties" className="back-link">← Back to all properties</Link>

          <div className="property-detail">
            <PropertyGallery
              images={property.gallery && property.gallery.length ? property.gallery : [property.img]}
              alt={property.name}
            />

            <div className="reveal">
              <div className="prop-price-row">
                <div className="prop-price">From {property.price}</div>
                <ShareButton
                  title={`${property.name} — Earth Link Real Estate`}
                  text={`${property.name} in ${property.location}. ${property.type}, from ${property.price}.`}
                />
              </div>

              <dl className="detail-spec">
                <div><dt>Type</dt><dd>{property.type}</dd></div>
                <div><dt>Bedrooms</dt><dd>{property.beds}</dd></div>
                <div><dt>Area</dt><dd>{property.area}</dd></div>
                <div><dt>Location</dt><dd>{property.location}</dd></div>
                <div><dt>Reference</dt><dd>{property.ref}</dd></div>
                <div><dt>DLD Permit</dt><dd>{property.permit}</dd></div>
              </dl>

              {property.description.map((paragraph, i) => (
                <p className="prose" key={i} style={{ marginBottom: 16 }}>
                  {paragraph}
                </p>
              ))}

              <div className="hero-btns" style={{ marginTop: 30 }}>
                <Link href="/contact" className="btn btn-gold">Enquire about this property</Link>
                <Link href="/properties" className="btn btn-glass">View all properties</Link>
              </div>

              {property.url && (
                <div style={{ marginTop: 30 }}>
                  <PropertyQr url={property.url} />
                  <p className="table-note" style={{ marginTop: 12 }}>Scan to view on Bayut</p>
                </div>
              )}

              <p className="table-note" style={{ marginTop: 24 }}>
                Listed by Earth Link Real Estate. Contact us for the DLD permit and full documentation.
              </p>
            </div>
          </div>
        </div>
      </section>
    </article>
  );
}
